version: '3'

services:
  flask-web:
    build: .
    container_name: flask-web
    ports:
     - "80"
  
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    